2024-01-16 13:16:11,475:DEBUG:certbot._internal.main:certbot version: 2.8.0
2024-01-16 13:16:11,475:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-01-16 13:16:11,475:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'tjfgkssk9472@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'tairot.online']
2024-01-16 13:16:11,475:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-01-16 13:16:11,563:DEBUG:certbot._internal.log:Root logging level set at 30
2024-01-16 13:16:11,565:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-01-16 13:16:11,566:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0xffffb37dca30>
Prep: True
2024-01-16 13:16:11,566:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0xffffb37dca30> and installer None
2024-01-16 13:16:11,566:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-01-16 13:16:11,618:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1519022676', new_authzr_uri=None, terms_of_service=None), 053f50e92556dc2ae6fb1958ad04b4cb, Meta(creation_dt=datetime.datetime(2024, 1, 16, 8, 39, 49, tzinfo=<UTC>), creation_host='1b0b13fa81e7', register_to_eff=None))>
2024-01-16 13:16:11,618:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-01-16 13:16:11,620:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-01-16 13:16:12,271:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-01-16 13:16:12,277:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 13:16:12 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "irLWIm-dM14": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-01-16 13:16:12,280:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for tairot.online
2024-01-16 13:16:12,286:DEBUG:acme.client:Requesting fresh nonce
2024-01-16 13:16:12,291:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-01-16 13:16:12,505:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-01-16 13:16:12,506:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 13:16:12 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4dBlQ8jZefbTN5ET9NIlfI07NJhxUhtLntV91F_Mi7tdc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-01-16 13:16:12,507:DEBUG:acme.client:Storing nonce: wFJtXv4dBlQ8jZefbTN5ET9NIlfI07NJhxUhtLntV91F_Mi7tdc
2024-01-16 13:16:12,508:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "tairot.online"\n    }\n  ]\n}'
2024-01-16 13:16:12,512:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZEJsUThqWmVmYlRONUVUOU5JbGZJMDdOSmh4VWh0TG50VjkxRl9NaTd0ZGMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "WGEio5GPGVhn_MMzOC0dDugZGSyx_UPO7M7N2H3lghzzWWrbQHJGzq4fhrPy7fU4rMh_xZz6j4EKUIzzex7eoV7gYhksZyjAaVhUeYm4aQ8avy5wYYSnAytzDvMCcCXWC6gyHVXlU5q46bS4WWtJ3K_gabprDZvksmasiMq8k27WPg7yP8C403rMFKt22Fxn5ZXZFNDlf6sWGA09moFKooL3y-dt8Ne1e9mE3r6lrQJ3byvCZIXDU7Mict5LocBhcMUiIjJenI_pRU-AL5WmleE1hAptyQ8El6OxYyuaplj6Q3nR57gqxIDgCWTl30USb68Jf83LjFcw-MnaZDwqtQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInRhaXJvdC5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-01-16 13:16:12,983:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 339
2024-01-16 13:16:12,985:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Tue, 16 Jan 2024 13:16:12 GMT
Content-Type: application/json
Content-Length: 339
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1519022676/237115862306
Replay-Nonce: wFJtXv4dSznH6L_q8fek7VqlafULBY8FWFs_v4UukSgR7O808UM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-01-23T13:16:12Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "tairot.online"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/304804828446"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1519022676/237115862306"
}
2024-01-16 13:16:12,985:DEBUG:acme.client:Storing nonce: wFJtXv4dSznH6L_q8fek7VqlafULBY8FWFs_v4UukSgR7O808UM
2024-01-16 13:16:12,986:DEBUG:acme.client:JWS payload:
b''
2024-01-16 13:16:12,989:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/304804828446:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJ3Rkp0WHY0ZFN6bkg2TF9xOGZlazdWcWxhZlVMQlk4RldGc192NFV1a1NnUjdPODA4VU0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNDgwNDgyODQ0NiJ9",
  "signature": "SdYv6N-Q8DPe1sKKsInbLTvsTNKwBnDIje98CrC9xjEvzAeXoZ0MinvnK0JJ_mO6RK-yXVPtL5-M8sVYbpOLoEhNzbh_S5PkF1_zNNtKhvDjj9Hq5Q4wMwIyzXotS5d260hWFCKf6CKBvNFlYNiOH6I5CqP39XvVB_nH_hO55w5FTBqwpDrTDj3OYfSiF_dry6S01d3kV6fub_YnKhmJA_1BHCGPMcYPsCwlbjlD1QNAfShhEMvTXM7KcxnAfcbDoj5gFk-Dtuq9EokNSywBf2lUVdnDyRS19ZkVWAxlXSuJ1Kod0oZaOXHEVDD6Qc4wn1HsyBl2u03x-jPVgFir9A",
  "payload": ""
}
2024-01-16 13:16:13,219:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/304804828446 HTTP/1.1" 200 797
2024-01-16 13:16:13,220:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 13:16:13 GMT
Content-Type: application/json
Content-Length: 797
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: cBLV7b5iL386rJTa6wRi8FyyVRZQgn5ZyxiPzd4PTMFFWwvD95w
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "tairot.online"
  },
  "status": "pending",
  "expires": "2024-01-23T13:16:12Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/JPi-0A",
      "token": "CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/IsyGzg",
      "token": "CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/A4fSbw",
      "token": "CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho"
    }
  ]
}
2024-01-16 13:16:13,220:DEBUG:acme.client:Storing nonce: cBLV7b5iL386rJTa6wRi8FyyVRZQgn5ZyxiPzd4PTMFFWwvD95w
2024-01-16 13:16:13,220:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-01-16 13:16:13,221:INFO:certbot._internal.auth_handler:http-01 challenge for tairot.online
2024-01-16 13:16:13,221:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-01-16 13:16:13,222:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-01-16 13:16:13,224:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho
2024-01-16 13:16:13,236:DEBUG:acme.client:JWS payload:
b'{}'
2024-01-16 13:16:13,239:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/JPi-0A:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJjQkxWN2I1aUwzODZySlRhNndSaThGeXlWUlpRZ241Wnl4aVB6ZDRQVE1GRld3dkQ5NXciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzMwNDgwNDgyODQ0Ni9KUGktMEEifQ",
  "signature": "TLOrCiJYRzRodW9rMwaQYPSMv8PNDeW2snmmATlI_JuNBaw_Co7zauJi-arge3UKS2g8xMpPX4qVoqaxPIOFDEnf7Q7Xa33MRNSrAEXqBkAxXyl4o-RUR3A4tbTErLgA_0BaMltyKHb01iQGPSzKmkUdQgDPWAPUAjPVcpcAVFr1N90eA8-4bs_q3whxbbrqDmuCG5YfM_pqLB_2YNOyIH1YZ7xm2eBYThrA8zi7ekBkgdvAlp_Lfk7yOA7EWUWaFa4UZCjs25dj3voV73bmuPGjrgOGVQC1MhWIHySB74PoSRNu-eY8rWn5jB8Q7NX2WMk9wH95MSFL48B2tolbfA",
  "payload": "e30"
}
2024-01-16 13:16:13,472:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/304804828446/JPi-0A HTTP/1.1" 200 187
2024-01-16 13:16:13,479:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 13:16:13 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/304804828446>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/JPi-0A
Replay-Nonce: cBLV7b5iGCeDHi0VFtjFtCLQtBs9hvkoZYDcNB9yvRMXdntZGbU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/JPi-0A",
  "token": "CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho"
}
2024-01-16 13:16:13,482:DEBUG:acme.client:Storing nonce: cBLV7b5iGCeDHi0VFtjFtCLQtBs9hvkoZYDcNB9yvRMXdntZGbU
2024-01-16 13:16:13,483:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-01-16 13:16:14,490:DEBUG:acme.client:JWS payload:
b''
2024-01-16 13:16:14,499:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/304804828446:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTUxOTAyMjY3NiIsICJub25jZSI6ICJjQkxWN2I1aUdDZURIaTBWRnRqRnRDTFF0QnM5aHZrb1pZRGNOQjl5dlJNWGRudFpHYlUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMwNDgwNDgyODQ0NiJ9",
  "signature": "SCkB7jo3iPENLuj96BHBdbWyzlGfHiFwNG0mpHd6bGaardw9gXxohdtceWFBsIQkEtnRRRvEOqdKCBj9dqWT8XfKKsYnWhpu244PAksGhCtMsFmEUHea8n6Yf5dsiME3b5vuzXJhP9FY1-8GmYWJqtlw2cmXW6Xho4Zb9M67MLRfGiRkh6mLBcX3ioSiK09ZUwB9uYbc71JbvB5Mzf5TtnHopEHUSpUv2ne3H0qlb9sr8sa2MG1XFYiTBgDR7_-8AikAcGoArOAb9btmh6ELIoawJM_TC2JlzbouUdyLjgDpgQeUiJdeXlcnGk-6e2SQQl8UiPfGdW-NFTp0KQaOpQ",
  "payload": ""
}
2024-01-16 13:16:14,733:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/304804828446 HTTP/1.1" 200 1220
2024-01-16 13:16:14,736:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 16 Jan 2024 13:16:14 GMT
Content-Type: application/json
Content-Length: 1220
Connection: keep-alive
Boulder-Requester: 1519022676
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: wFJtXv4dhWFjoJ-aBihesDs0mhngFccME0sE9Xjru61hDxIl9Co
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "tairot.online"
  },
  "status": "invalid",
  "expires": "2024-01-23T13:16:12Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "43.202.208.226: Invalid response from http://tairot.online/.well-known/acme-challenge/CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho: \"\u003c!DOCTYPE html\u003e\\n\u003chtml lang=\\\"en\\\"\u003e\\n  \u003chead\u003e\\n    \u003cscript type=\\\"module\\\"\u003e\\nimport RefreshRuntime from \\\"/@react-refresh\\\"\\nRefreshRuntime\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/304804828446/JPi-0A",
      "token": "CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho",
      "validationRecord": [
        {
          "url": "http://tairot.online/.well-known/acme-challenge/CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho",
          "hostname": "tairot.online",
          "port": "80",
          "addressesResolved": [
            "43.202.208.226"
          ],
          "addressUsed": "43.202.208.226"
        }
      ],
      "validated": "2024-01-16T13:16:13Z"
    }
  ]
}
2024-01-16 13:16:14,737:DEBUG:acme.client:Storing nonce: wFJtXv4dhWFjoJ-aBihesDs0mhngFccME0sE9Xjru61hDxIl9Co
2024-01-16 13:16:14,738:INFO:certbot._internal.auth_handler:Challenge failed for domain tairot.online
2024-01-16 13:16:14,739:INFO:certbot._internal.auth_handler:http-01 challenge for tairot.online
2024-01-16 13:16:14,739:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: tairot.online
  Type:   unauthorized
  Detail: 43.202.208.226: Invalid response from http://tairot.online/.well-known/acme-challenge/CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho: "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <script type=\"module\">\nimport RefreshRuntime from \"/@react-refresh\"\nRefreshRuntime"

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-01-16 13:16:14,740:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-01-16 13:16:14,741:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-01-16 13:16:14,741:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-01-16 13:16:14,742:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/CrvxDbQ97bK_ryjGE-yKU-Jo6sT2j0Yzl-OmrWBN_Ho
2024-01-16 13:16:14,744:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-01-16 13:16:14,745:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-01-16 13:16:14,747:ERROR:certbot._internal.log:Some challenges have failed.
